### ISSUE TITLE
Implicit declaration of function Remove_duplicate_shortcuts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BackupGGCode/grafx2#430]
```
I've just updated the gentoo ebuild to work with grafx2-2.3.1771 
and at the end of the compilation the system outputted me this:


 * QA Notice: Package has poor programming practices which may compile
 *            fine but exhibit random runtime failures.
 * main.c:664: warning: implicit declaration of function ‘Remove_duplicate_shortcuts’

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: http://code.google.com/p/grafx2/

A quick smoke test on the program, proved to work fine, so this isn't urgent at 
all.

Thanks.
```

Original issue reported on code.google.com by `00.rgb.s...@gmail.com` on 10 Apr 2011 at 10:59
